const $ = (s) => document.querySelector(s), $$ = (s) => [...document.querySelectorAll(s)];
const API_URL = localStorage.getItem("mindpulse-api-url") || "http://localhost:8000";
const KEYS = { auth: "mindpulse-auth-v1", baby: "mindpulse-baby-v1", history: "mindpulse-baby-history-v2", model: "mindpulse-baby-q-v2", settings: "mindpulse-baby-settings-v2" };
const ACTIONS = ["noNoise", "whiteNoise", "pinkNoise", "brownNoise", "softLullaby"], STATES = ["sleeping", "restless", "awake"], ACTION_NAMES = { noNoise: "No sound playing", whiteNoise: "Playing: White Noise", pinkNoise: "Playing: Pink Noise", brownNoise: "Playing: Brown Noise", softLullaby: "Playing: Soft Lullaby" };
const e = { activity: $("#activity-value"), ambient: $("#ambient-value"), ambientToggle: $("#ambient-toggle"), auth: $("#auth-button"), canvas: $("#waveform"), chart: $("#trend-chart"), chartDays: $("#chart-days"), demo: $("#demo-button"), history: $("#history-list"), learning: $("#learning-label"), monitor: $("#monitor-button"), monitorDuration: $("#monitor-duration"), monitorLabel: $("#monitor-label"), monitoringStatus: $("#monitoring-status"), pageTitle: $("#page-title"), progressContent: $("#progress-content"), progressLocked: $("#progress-locked"), response: $("#response-title"), responseDescription: $("#response-description"), responseMeter: $("#response-meter"), rustle: $("#rustle-value"), score: $("#sleep-score"), scoreRing: $("#score-ring"), sidebarCopy: $("#sidebar-copy"), sidebarProgress: $("#sidebar-progress"), sidebarScore: $("#sidebar-score"), signalDot: $("#signal-dot"), sleepDescription: $("#sleep-description"), sleepState: $("#sleep-state-title"), toast: $("#toast"), training: $("#training-toggle"), waveState: $("#wave-state"), recordingDot: $("#recording-dot") };
const monitor = { active: false, analyser: null, audioContext: null, data: null, freq: null, frame: null, samples: [], stream: null, source: null, startedAt: null, wakeLock: null, nightId: null, events: [], eventStart: null, lastState: null };
const playback = { context: null, nodes: [], timer: null };
let settings = read(KEYS.settings, { ambientEnabled: true, trainingEnabled: false }), history = readHistory(), q = readModel(), auth = read(KEYS.auth, null), baby = read(KEYS.baby, null), current = { state: "sleeping", action: "noNoise", score: 82, features: { activitySpike: .04, rustleDensity: .08, ambientFloor: .03 } };
function read(key, fallback) { try { const value = JSON.parse(localStorage.getItem(key)); return value && typeof value === "object" ? { ...fallback, ...value } : fallback; } catch { return fallback; } }
function save(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
function readModel() { const saved = read(KEYS.model, {}), starter = { sleeping: { noNoise: 1.5 }, restless: { pinkNoise: 1.5 }, awake: { whiteNoise: 1.5 } }; return Object.fromEntries(STATES.map((state) => [state, Object.fromEntries(ACTIONS.map((action) => [action, Number(saved[state]?.[action]) || starter[state][action] || 0]))])); }
function readHistory() { const local = read(KEYS.history, []); return local.length ? local : [74, 79, 70, 84, 76, 81, 82].map((score, i) => { const date = new Date(); date.setDate(date.getDate() - 6 + i); return { date: date.toISOString(), score, state: score < 62 ? "awake" : score < 77 ? "restless" : "sleeping" }; }); }
const avg = (a) => a.length ? a.reduce((x, y) => x + y, 0) / a.length : 0, clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
function toast(text) { e.toast.textContent = text; e.toast.classList.add("is-visible"); clearTimeout(toast.timer); toast.timer = setTimeout(() => e.toast.classList.remove("is-visible"), 3600); }
function api(path, options = {}) { return fetch(`${API_URL}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(auth?.token ? { Authorization: `Bearer ${auth.token}` } : {}), ...options.headers } }).then(async (r) => { const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.detail || "Could not save right now"); return data; }); }
function stateFor(f) { return f.activitySpike > .22 || (f.rustleDensity > .6 && f.activitySpike > .12) ? "awake" : f.activitySpike > .08 || f.rustleDensity > .27 ? "restless" : "sleeping"; }
function scoreFor(f, state) { return Math.round(clamp(100 - f.activitySpike * 155 - f.rustleDensity * 35 - f.ambientFloor * 18 - (state === "awake" ? 20 : state === "restless" ? 7 : 0), 20, 98)); }
function choose(state) { if (!settings.ambientEnabled) return "noNoise"; if (Math.random() < .12) return ACTIONS[Math.floor(Math.random() * ACTIONS.length)]; return ACTIONS.reduce((best, action) => q[state][action] > q[state][best] ? action : best, ACTIONS[0]); }
function learn(from, action, to) { const reward = to === "sleeping" ? 10 : to === "awake" ? -10 : -2, best = Math.max(...ACTIONS.map((a) => q[to][a])); q[from][action] += .28 * (reward + .72 * best - q[from][action]); save(KEYS.model, q); }
function label(state) { return state === "sleeping" ? ["Deep sleep", "Low activity and a steady room baseline."] : state === "restless" ? ["Restless", "Low-to-mid sound shifts suggest the room may be unsettled."] : ["Active disturbance", "A larger activity spike was detected. Check the room directly if you are concerned."]; }
function level(value, a, b, words) { return value > b ? words[2] : value > a ? words[1] : words[0]; }
function render() { const [title, description] = label(current.state); e.sleepState.textContent = title; e.sleepDescription.textContent = description; e.score.textContent = e.sidebarScore.textContent = current.score; e.scoreRing.style.setProperty("--score", current.score); e.sidebarProgress.style.width = `${current.score}%`; e.sidebarCopy.textContent = current.state === "sleeping" ? "A calm baseline so far." : current.state === "restless" ? "Watching for a calmer window." : "A room check may be useful."; e.activity.textContent = level(current.features.activitySpike, .08, .22, ["Low", "Rising", "High"]); e.rustle.textContent = level(current.features.rustleDensity, .27, .6, ["Low", "Moderate", "Frequent"]); e.ambient.textContent = level(current.features.ambientFloor, .06, .16, ["Quiet", "Present", "Elevated"]); e.signalDot.className = `signal-dot ${current.state}`; e.response.textContent = ACTION_NAMES[current.action]; e.responseDescription.textContent = settings.ambientEnabled ? `Local model selected this response for a ${title.toLowerCase()} state.` : "Ambient responses are paused by parent control."; e.responseMeter.style.width = `${clamp(Math.max(...ACTIONS.map((a) => q[current.state][a])) * 4 + 15, 12, 90)}%`; e.learning.textContent = "Local learning: adapting to this room"; e.ambientToggle.textContent = `Ambient response: ${settings.ambientEnabled ? "on" : "off"}`; e.training.checked = settings.trainingEnabled; }
function addHistory() { const now = new Date(), last = history.at(-1), sameHour = last && new Date(last.date).getHours() === now.getHours() && new Date(last.date).toDateString() === now.toDateString(), entry = { date: now.toISOString(), score: current.score, state: current.state }; sameHour ? history[history.length - 1] = entry : history.push(entry); history = history.slice(-30); save(KEYS.history, history); renderHistory(); }
function renderHistory() { e.history.innerHTML = history.slice(-4).reverse().map((x) => `<article><time>${new Date(x.date).toDateString() === new Date().toDateString() ? "Tonight" : new Intl.DateTimeFormat("en", { month: "short", day: "numeric" }).format(new Date(x.date))}</time><strong>${x.score}<small>/100</small></strong><p>${x.state === "sleeping" ? "Settled window" : x.state === "restless" ? "Restless window" : "Active window"}</p><i><b style="width:${x.score}%"></b></i></article>`).join(""); }
function renderChart(entries = history.slice(-7)) { const scores = entries.map((x) => x.quality ?? x.score ?? 0), w = 700, h = 245, pad = 15, points = scores.map((s, i) => [pad + (w - pad * 2) * i / Math.max(scores.length - 1, 1), pad + (98 - s) / 78 * (h - pad * 2)]), line = points.map((p) => p.join(",")).join(" "); e.chart.innerHTML = `<polyline points="${line}" fill="none" stroke="#89bfb1" stroke-width="4" stroke-linecap="round"/>${points.map(([x,y]) => `<circle cx="${x}" cy="${y}" r="4" fill="#141817" stroke="#89bfb1" stroke-width="2"/>`).join("")}`; e.chartDays.innerHTML = entries.map((x) => `<span>${new Intl.DateTimeFormat("en", { weekday: "short" }).format(new Date(x.date))}</span>`).join(""); }
function draw(data, phase = 0) { const c = e.canvas.getContext("2d"), w = e.canvas.clientWidth || 740, h = e.canvas.clientHeight || 176, d = devicePixelRatio || 1; if (e.canvas.width !== w * d) { e.canvas.width = w * d; e.canvas.height = h * d; } c.setTransform(d, 0, 0, d, 0, 0); c.clearRect(0,0,w,h); c.strokeStyle = "rgba(137,191,177,.18)"; c.beginPath(); c.moveTo(0,h/2); c.lineTo(w,h/2); c.stroke(); c.strokeStyle = "#89bfb1"; c.lineWidth = 2; c.beginPath(); for(let i=0;i<150;i++){const x=i/149*w, v=data?(data[Math.floor(i/149*(data.length-1))]-128)/128:Math.sin(i*.2+phase)*.08+Math.sin(i*.08-phase)*.04, y=h/2+v*h*(data?.39:1);i?c.lineTo(x,y):c.moveTo(x,y)} c.stroke(); }
function idle(t=0) { if (!monitor.active) { draw(null,t/1000); monitor.frame=requestAnimationFrame(idle); } }
function wave(text, live=false) { e.waveState.textContent=text; e.waveState.classList.toggle("is-live",live); e.recordingDot.classList.toggle("is-live",live); }
function features() { monitor.analyser.getByteTimeDomainData(monitor.data); monitor.analyser.getByteFrequencyData(monitor.freq); const time=[...monitor.data].map((x)=>(x-128)/128), rms=Math.sqrt(avg(time.map((x)=>x*x))), lowEnd=Math.max(2,Math.floor(monitor.freq.length*.1)), midEnd=Math.floor(monitor.freq.length*.38), low=avg([...monitor.freq.slice(1,lowEnd)])/255, mid=avg([...monitor.freq.slice(lowEnd,midEnd)])/255, floor=clamp(low*.6+rms*.4,0,1), previous=monitor.samples.at(-1)?.rms||rms, f={activitySpike:clamp(Math.max(0,rms-floor*.55)*4+Math.max(0,rms-previous)*5,0,1),ambientFloor:floor,rustleDensity:clamp(mid*1.5+Math.abs(rms-previous)*5,0,1)}; monitor.samples.push({...f,rms}); if(monitor.samples.length>120)monitor.samples.shift(); return f; }
async function flushEvents() { if (!auth || !baby || !monitor.nightId || !monitor.events.length) return; const events=monitor.events.splice(0).map((x)=>({...x,sound_response:{noNoise:"none",whiteNoise:"white",pinkNoise:"pink",brownNoise:"brown",softLullaby:"lullaby"}[x.sound_response]})); try { await api(`/api/nights/${monitor.nightId}/events`,{method:"POST",body:JSON.stringify({events})}); } catch { monitor.events.unshift(...events); } }
function recordEvent(now) { if (!monitor.eventStart) { monitor.eventStart=now; monitor.lastState=current.state; return; } monitor.events.push({event_type:{sleeping:"deep_sleep",restless:"restless",awake:"active_disturbance"}[monitor.lastState],started_at:monitor.eventStart.toISOString(),ended_at:now.toISOString(),sound_response:current.action,resettle_seconds:current.state==="sleeping"&&monitor.lastState==="awake"?Math.round((now-monitor.eventStart)/1000):null}); monitor.eventStart=now; monitor.lastState=current.state; if(monitor.events.length>=5)flushEvents(); }
function process(f) { const previousState=current.state, previousAction=current.action, nextState=stateFor(f); if(monitor.samples.length>8)learn(previousState,previousAction,nextState); current={features:f,state:nextState,score:scoreFor(f,nextState),action:choose(nextState)}; render(); addHistory(); recordEvent(new Date()); if(settings.ambientEnabled&&current.action!==previousAction)play(current.action); if(settings.trainingEnabled&&auth&&baby) api(`/api/babies/${baby.id}/training-contributions`,{method:"POST",body:JSON.stringify({...f,sleep_state:{sleeping:"deep_sleep",restless:"restless",awake:"active_disturbance"}[nextState]})}).catch(()=>{}); }
function loop() { if(!monitor.active)return; const f=features(); draw(monitor.data); if(monitor.samples.length%60===0)process(f); e.monitorDuration.textContent=`${Math.floor((Date.now()-monitor.startedAt)/60000)} min active`; monitor.frame=requestAnimationFrame(loop); }
function makeNoise(ctx, kind) { const buffer=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate), d=buffer.getChannelData(0); let pink=[0,0,0,0,0,0,0], brown=0; for(let i=0;i<d.length;i++){const white=Math.random()*2-1;if(kind==="brownNoise"){brown=clamp((brown+white*.02)/1.02,-1,1);d[i]=brown*.18}else if(kind==="pinkNoise"){pink[0]=.99886*pink[0]+white*.0555179;pink[1]=.99332*pink[1]+white*.0750759;pink[2]=.969*pink[2]+white*.153852;pink[3]=.8665*pink[3]+white*.3104856;pink[4]=.55*pink[4]+white*.5329522;pink[5]=-.7616*pink[5]-white*.016898;d[i]=(pink.reduce((a,b)=>a+b)+white*.5362)*.11;pink[6]=white*.115926}else d[i]=white*.1} return buffer; }
function stopSound(){playback.nodes.forEach((n)=>{try{n.stop?.();n.disconnect?.()}catch{}});playback.nodes=[];clearTimeout(playback.timer)}
function play(action, duration=300000){stopSound();if(action==="noNoise")return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ctx=playback.context||new C();playback.context=ctx;ctx.resume();const gain=ctx.createGain();gain.gain.value=.08;gain.connect(ctx.destination);playback.nodes.push(gain);if(action==="softLullaby"){[261.63,329.63,392,329.63].forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=f;o.type="sine";g.gain.setValueAtTime(0,ctx.currentTime+i*1.4);g.gain.linearRampToValueAtTime(.025,ctx.currentTime+i*1.4+.25);g.gain.linearRampToValueAtTime(0,ctx.currentTime+i*1.4+1.25);o.connect(g).connect(gain);o.start();o.stop(ctx.currentTime+5.8);playback.nodes.push(o,g)})}else{const s=ctx.createBufferSource();s.buffer=makeNoise(ctx,action);s.loop=true;s.connect(gain);s.start();playback.nodes.push(s)}playback.timer=setTimeout(()=>{stopSound();current.action="noNoise";render()},duration)}
async function lock(){try{monitor.wakeLock=await navigator.wakeLock?.request("screen")}catch{}}
async function start(){if(!navigator.mediaDevices?.getUserMedia)return toast("Monitoring needs a modern browser microphone.");try{const stream=await navigator.mediaDevices.getUserMedia({audio:{autoGainControl:false,echoCancellation:false,noiseSuppression:false}}),C=window.AudioContext||window.webkitAudioContext,ctx=new C();await ctx.resume();const analyser=ctx.createAnalyser();analyser.fftSize=2048;analyser.smoothingTimeConstant=.75;const source=ctx.createMediaStreamSource(stream);source.connect(analyser);Object.assign(monitor,{active:true,stream,source,audioContext:ctx,analyser,data:new Uint8Array(analyser.fftSize),freq:new Uint8Array(analyser.frequencyBinCount),samples:[],startedAt:Date.now(),events:[],eventStart:null,lastState:null});await lock();if(auth&&baby){try{monitor.nightId=(await api("/api/nights",{method:"POST",body:JSON.stringify({baby_id:baby.id})})).night_session_id}catch{toast("Listening locally; sync is unavailable right now.")}}e.monitor.classList.add("is-monitoring");e.monitorLabel.textContent="Stop room monitoring";e.monitoringStatus.textContent="Monitoring active";wave("Monitoring locally",true);loop()}catch{toast("Microphone access was not granted. Run demo to explore.")}}
async function stop(){monitor.active=false;cancelAnimationFrame(monitor.frame);recordEvent(new Date());await flushEvents();if(monitor.nightId){try{await api(`/api/nights/${monitor.nightId}/end`,{method:"POST",body:JSON.stringify({sleep_quality_score:current.score})})}catch{}}monitor.stream?.getTracks().forEach((t)=>t.stop());monitor.source?.disconnect();await monitor.audioContext?.close();monitor.wakeLock?.release?.();Object.assign(monitor,{nightId:null,stream:null,source:null,audioContext:null,wakeLock:null});stopSound();e.monitor.classList.remove("is-monitoring");e.monitorLabel.textContent="Start room monitoring";e.monitorDuration.textContent="Paused";e.monitoringStatus.textContent="Monitoring paused";wave("Room monitoring paused");idle()}
function demo(){const f={activitySpike:.29,ambientFloor:.09,rustleDensity:.67};process(f);play(current.action);wave("Demo disturbance analyzed");toast(`${ACTION_NAMES[current.action]} selected locally.`)}
function view(name){$$("[data-view]").forEach((x)=>x.classList.toggle("is-visible",x.dataset.view===name));$$("[data-view-target]").forEach((x)=>x.classList.toggle("is-active",x.dataset.viewTarget===name));e.pageTitle.textContent=name==="dashboard"?"Baby's Room Status":name==="progress"?"Progress":"Settings";$(".sidebar").classList.remove("is-open");scrollTo({top:0,behavior:"smooth"});if(name==="progress")loadProgress()}
async function loadProgress(){const signed=!!(auth&&baby);e.progressLocked.hidden=signed;e.progressContent.hidden=!signed;if(!signed)return;try{const p=await api(`/api/babies/${baby.id}/progress`);$("#quality-7").textContent=p.rolling_quality.days_7??"—";$("#wake-count").textContent=p.wake_events_30d;$("#best-noise").textContent=p.best_noise?`${p.best_noise.sound_response} · ${p.best_noise.average_resettle_seconds}s`:"Learning";renderChart(p.sessions.map((x)=>({date:x.date,quality:x.quality})))}catch{toast("Progress could not load right now.")}}
async function submitAuth(event){event.preventDefault();const mode=event.submitter.dataset.authMode,payload={email:$("#auth-email").value,password:$("#auth-password").value},babyName=$("#baby-name").value.trim();try{auth=await api(`/api/auth/${mode}`,{method:"POST",body:JSON.stringify(payload)});save(KEYS.auth,auth);if(babyName)baby=await api("/api/babies",{method:"POST",body:JSON.stringify({name:babyName})});else{const babies=await api("/api/babies");baby=babies[0]||null}if(baby)save(KEYS.baby,baby);$("#auth-dialog").close();e.auth.textContent=baby?`Saving progress for ${baby.name}`:"Add a baby profile";toast(baby?"Account connected. Derived events can now sync.":"Account created. Enter a baby's name next time to sync progress.");loadProgress()}catch(err){toast(err.message)}}
function init(){ $("#today-date").textContent=new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric"}).format(new Date());render();renderHistory();renderChart();idle();if("serviceWorker"in navigator)navigator.serviceWorker.register("/service-worker.js").catch(()=>{});e.auth.textContent=auth?(baby?`Saving progress for ${baby.name}`:"Add a baby profile"):"Sign in to save progress";e.monitor.onclick=()=>monitor.active?stop():start();e.demo.onclick=demo;$("#next-response").onclick=()=>{current.action=ACTIONS[(ACTIONS.indexOf(current.action)+1)%ACTIONS.length];play(current.action);render()};e.ambientToggle.onclick=()=>{settings.ambientEnabled=!settings.ambientEnabled;save(KEYS.settings,settings);if(!settings.ambientEnabled)stopSound();render()};e.training.onchange=()=>{settings.trainingEnabled=e.training.checked;save(KEYS.settings,settings);toast(settings.trainingEnabled?"Only derived numeric features may be shared when signed in.":"Detection contribution is off.")};$("#reset-learning").onclick=()=>{localStorage.removeItem(KEYS.model);q=readModel();render();toast("Local response learning was reset.")};$$('[data-view-target]').forEach((x)=>x.onclick=()=>view(x.dataset.viewTarget));$("#mobile-menu").onclick=()=>$(".sidebar").classList.toggle("is-open");$("#open-guide").onclick=$("#view-learning").onclick=()=>$("#info-dialog").showModal();$("#jump-to-monitor").onclick=()=>$("#monitor-card").scrollIntoView({behavior:"smooth"});e.auth.onclick=$("#progress-auth").onclick=()=>$("#auth-dialog").showModal();$("#auth-form").onsubmit=submitAuth;$$('.dialog-close').forEach((x)=>x.onclick=()=>x.closest("dialog").close());document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"&&monitor.active)lock()});}
init();
